jobs:
  include:
    - language: csharp
      os: windows
      solution: ./C#/hellocsharp.sln
      install:
        - nuget restore C#/hellocsharp.sln
      script:
        - msbuild /p:Configuration=Release ./C#/hellocsharp.sln

    - language: python
      python: 3.8
      script:
        - python ./Python/hellopython.py

    - language: c
      os: linux
      compiler: gcc 
      script:
        - gcc ./C/helloc.c -o hello